apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourites-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourites
  template:
    metadata:
      labels:
        app: favourites
    spec:
      containers:
        - image: ninavelikajne/favourites:2021-12-16-02-55-06
          name: favourites
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sewztpca
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: jviqrny5vLJYogFEeyBhAr7daifOAiwB
          ports:
            - containerPort: 4444
              name: server
              protocol: TCP
         

---

apiVersion: v1
kind: Service
metadata:
  name: favourites
spec:
  type: LoadBalancer
  ports:
    - port: 4444
      protocol: TCP
      targetPort: server
  selector:
    app: favourites
